#!/usr/bin/env bash
code --install-extension 42crunch.vscode-openapi
code --install-extension bmewburn.vscode-intelephense-client
code --install-extension clemenspeters.format-json
code --install-extension donjayamanne.githistory
code --install-extension editorconfig.editorconfig
code --install-extension github.copilot
code --install-extension github.copilot-chat
code --install-extension golang.go
code --install-extension honnamkuan.golang-snippets
code --install-extension junv.recent-files
code --install-extension mikestead.dotenv
code --install-extension mohsen1.prettify-json
code --install-extension ms-azuretools.vscode-containers
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-vscode.makefile-tools
code --install-extension ms-vscode.vscode-speech
code --install-extension redhat.vscode-yaml
code --install-extension rooveterinaryinc.roo-cline
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension steoates.autoimport
code --install-extension tabnine.tabnine-vscode-self-hosted-updater
code --install-extension trinm1709.dracula-theme-from-intellij
code --install-extension vue.volar
code --install-extension whatwedo.twig