code --install-extension alexkrechik.cucumberautocomplete
code --install-extension be5invis.toml
code --install-extension bmewburn.vscode-intelephense-client
code --install-extension bradgashler.htmltagwrap
code --install-extension christian-kohler.npm-intellisense
code --install-extension ClemensPeters.format-json
code --install-extension dbaeumer.vscode-eslint
code --install-extension donjayamanne.githistory
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension EditorConfig.EditorConfig
code --install-extension esbenp.prettier-vscode
code --install-extension fivethree.vscode-svelte-snippets
code --install-extension formulahendry.auto-rename-tag
code --install-extension gogocrow.webpack-snippets
code --install-extension golang.go
code --install-extension Gruntfuggly.activitusbar
code --install-extension jeremyrajan.webpack
code --install-extension jevakallio.vscode-live-frame
code --install-extension junv.recent-files
code --install-extension michelemelluso.code-beautifier
code --install-extension mikestead.dotenv
code --install-extension mohsen1.prettify-json
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension ms-vsliveshare.vsliveshare-audio
code --install-extension ms-vsliveshare.vsliveshare-pack
code --install-extension naumovs.color-highlight
code --install-extension negokaz.live-server-preview
code --install-extension OfHumanBondage.react-proptypes-intellisense
code --install-extension phplasma.csv-to-table
code --install-extension PKief.material-icon-theme
code --install-extension pnp.polacode
code --install-extension redhat.vscode-commons
code --install-extension redhat.vscode-yaml
code --install-extension ritwickdey.LiveServer
code --install-extension rust-lang.rust
code --install-extension rvest.vs-code-prettier-eslint
code --install-extension Shan.code-settings-sync
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension skyapps.fish-vscode
code --install-extension steoates.autoimport
code --install-extension svelte.svelte-vscode
code --install-extension syler.sass-indented
code --install-extension sysoev.language-stylus
code --install-extension Togusa09.tmlanguage
code --install-extension trinm1709.dracula-theme-from-intellij
code --install-extension xabikos.JavaScriptSnippets
code --install-extension yzhang.markdown-all-in-one
code --install-extension Zignd.html-css-class-completion